"""
Regenerates docs/executive_report.pdf from the current evaluation/*.csv and
models/metrics.json, so the report can never drift out of sync with the
actual evaluation run (Task 5 deliverable, backed by Task 2 results).

Run with:  python -m docs.generate_report   (from the project root)
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, PageBreak)

ROOT = Path(__file__).resolve().parents[1]


def load_eval():
    with open(ROOT / "evaluation" / "category_summary.csv") as f:
        rows = list(csv.DictReader(f))
    with open(ROOT / "evaluation" / "combined_evaluation_results.csv") as f:
        cases = list(csv.DictReader(f))
    metrics = json.loads((ROOT / "models" / "metrics.json").read_text())
    return rows, cases, metrics


def build():
    summary, cases, metrics = load_eval()
    total_cases = sum(int(r["cases"]) for r in summary)
    total_passes = sum(int(r["passes"]) for r in summary)
    weakest = min(summary, key=lambda r: float(r["pass_rate"]))

    styles = getSampleStyleSheet()
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9.5, leading=13, spaceAfter=6)
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=15, spaceAfter=8)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=11.5, spaceAfter=4, spaceBefore=6)

    story = []
    story.append(Paragraph("Week 3 Day 5 — AFL Assistant Executive Report", h1))

    story.append(Paragraph("Product goal.", h2))
    story.append(Paragraph(
        "Ship a domain-locked AFL assistant combining factual Q&amp;A, structured statistics and "
        "probabilistic prediction behind explicit routing and validation. Unsupported sports and "
        "prompt-injection attempts are refused rather than answered out of scope.", body))

    story.append(Paragraph("Architecture.", h2))
    story.append(Paragraph(
        "Request &#8594; AFL scope/injection gate &#8594; router &#8594; direct AFL answer / retrieval / "
        "prediction / refusal &#8594; validation &#8594; response. FastAPI exposes <b>/chat</b> with "
        "message + conversation_id; the optional Streamlit UI uses the same endpoint. Every tool/model "
        "call runs under a hard timeout, and requests are rate-limited per client. Prediction outputs "
        "use one centralized disclaimer: \u201cPredicted probability, not a certainty.\u201d", body))

    story.append(Paragraph("Evaluation.", h2))
    story.append(Paragraph(
        f"The regression suite contains {total_cases} cases across four categories, generated by "
        f"running the live pipeline end-to-end (<i>evaluation/run_eval.py</i>) rather than hand-authored "
        f"expectations. The supplied 2025 holdout contains {metrics['n']} matches. The reproducible "
        f"match model achieved {metrics['accuracy']*100:.2f}% accuracy and {metrics['macro_f1']:.4f} macro "
        f"F1; the naive ladder-position baseline achieved {metrics['ladder_baseline_accuracy']*100:.2f}%. "
        f"This is a transparent internal benchmark, not a bookmaker/public forecast claim.", body))

    story.append(Paragraph("Results by category.", h2))
    table_data = [["Category", "Cases", "Passes", "Pass rate"]]
    for r in summary:
        table_data.append([r["category"], r["cases"], r["passes"], f"{float(r['pass_rate'])*100:.0f}%"])
    table_data.append(["Total", str(total_cases), str(total_passes), f"{total_passes/total_cases*100:.0f}%"])
    t = Table(table_data, colWidths=[2.6*inch, 0.9*inch, 0.9*inch, 1.0*inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#e5e7eb")),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))

    story.append(Paragraph("Weakest category &amp; improvement.", h2))
    story.append(Paragraph(
        f"All categories currently pass at {float(weakest['pass_rate'])*100:.0f}% or above, but "
        f"<b>Multi-turn coherence</b> is the weakest by design margin rather than by pass rate: the "
        f"pipeline is stateless per call (<i>conversation_id</i> is logged but not yet used to recall "
        f"prior turns), so a follow-up like \u201cwhat about 2023?\u201d only works if it happens to be "
        f"self-contained. <b>Concrete improvement:</b> persist per-conversation turn history "
        f"(team/season/last intent) keyed by <i>conversation_id</i> and have the router resolve "
        f"pronouns/ellipsis (\u201cthat\u201d, \u201cthem\u201d, \u201cwhat about &lt;year&gt;\u201d) against "
        f"it before falling back to a clarification.", body))

    story.append(Paragraph("Known limitations.", h2))
    story.append(Paragraph(
        "The supplied data ends on 2025-09-27, so the system does not invent 2026 fixtures. Production "
        "requires a live fixture/results source. AFL outcomes are noisy; player availability/selection is "
        "not fully modeled. Monitoring therefore focuses on drift and calibration rather than promising "
        "perfect forecasts.", body))

    story.append(PageBreak())

    story.append(Paragraph("Production Hardening, Monitoring &amp; Next Steps", h1))

    story.append(Paragraph("Hardening.", h2))
    story.append(Paragraph(
        "Scope checks run before retrieval or prediction; injection-like requests are refused. "
        "Unresolved entities/dates produce clarification instead of guesses. API inputs are bounded, "
        "every tool/model call runs under a hard timeout, requests are rate-limited per client IP, and "
        "repeated off-topic/injection attempts are counted per conversation and flagged in the logs. "
        "Structured logs capture query, intent, tools called, latency, token usage and prediction "
        "metadata.", body))

    story.append(Paragraph("Monitoring.", h2))
    story.append(Paragraph(
        "Track p50/p95 latency, API 5xx rate, tool/model error rate, off-topic leak rate, prediction "
        "accuracy and calibration. Starting alerts: p95 &gt;3s for 15 minutes; API 5xx &gt;2% for 15 "
        "minutes; tool/model errors &gt;3% daily; any confirmed off-topic leak; or a rolling accuracy "
        "drop &gt;5 percentage points versus the previous window.", body))

    story.append(Paragraph("Weekly refresh loop.", h2))
    story.append(Paragraph(
        "Ingest completed results &#8594; validate schema/duplicates &#8594; recompute leakage-safe "
        "features &#8594; run the regression suite &#8594; compare against the ladder baseline &#8594; "
        "retrain only if acceptance checks pass &#8594; version model/data/schema &#8594; deploy with "
        "rollback.", body))

    story.append(Paragraph("Next steps.", h2))
    story.append(Paragraph(
        "Connect a live fixture/results provider; add confirmed player-selection inputs; move "
        "conversation state to durable, cross-turn storage; move rate limiting to a shared "
        "store/API-gateway for multi-instance deployments; expand adversarial and calibration "
        "evaluation; keep the current model available for rollback.", body))

    story.append(Paragraph("Demo.", h2))
    story.append(Paragraph(
        "The included 5\u20137 minute script/deck shows a factual question, dated prediction, "
        "off-topic/injection refusal and multi-turn conversation, followed by evaluation and "
        "monitoring.", body))

    doc = SimpleDocTemplate(str(ROOT / "docs" / "executive_report.pdf"), pagesize=letter,
                             topMargin=0.6*inch, bottomMargin=0.6*inch,
                             leftMargin=0.7*inch, rightMargin=0.7*inch)
    doc.build(story)


if __name__ == "__main__":
    build()
    print("Wrote docs/executive_report.pdf")
