"""
Regenerates docs/stakeholder_demo_slides.pptx from the current evaluation
results and model metrics.

Run with:  python -m docs.generate_slides   (from the project root)
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt

ROOT = Path(__file__).resolve().parents[1]


def load_eval():
    with open(ROOT / "evaluation" / "category_summary.csv") as f:
        rows = list(csv.DictReader(f))
    metrics = json.loads((ROOT / "models" / "metrics.json").read_text())
    total_cases = sum(int(r["cases"]) for r in rows)
    return total_cases, metrics


def add_slide(prs, title, bullets):
    layout = prs.slide_layouts[1]  # Title and Content
    slide = prs.slides.add_slide(layout)
    slide.shapes.title.text = title
    body = slide.placeholders[1].text_frame
    body.clear()
    for i, b in enumerate(bullets):
        p = body.paragraphs[0] if i == 0 else body.add_paragraph()
        p.text = b
        p.font.size = Pt(18)
    return slide


def build():
    total_cases, metrics = load_eval()

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "AFL Assistant Capstone"
    title_slide.placeholders[1].text = "Week 3 Day 5 \u2022 Ship, evaluate, monitor"

    add_slide(prs, "Product goal", [
        "Domain-locked AFL chat + structured retrieval + probabilistic prediction",
        "Explicit routing and validation",
        "Safe refusal for off-topic/injection attempts",
    ])

    add_slide(prs, "Architecture", [
        "API / UI \u2192 scope + injection gate \u2192 router",
        "\u2192 retrieval / prediction / direct AFL answer / refusal \u2192 validation \u2192 response + logs",
        "Every tool call runs under a hard timeout; requests are rate-limited",
    ])

    add_slide(prs, "Live demo", [
        "Factual: Carlton 2024 record",
        "Prediction: dated Cats vs Suns matchup",
        "Off-topic: IPL / Valorant refusal",
        "Multi-turn: probing \u2192 refused \u2192 returns to a valid AFL question",
    ])

    add_slide(prs, "Evaluation", [
        f"{total_cases} regression cases, generated by running the live pipeline",
        f"2025 holdout: {metrics['n']} matches",
        f"Model accuracy: {metrics['accuracy']*100:.2f}%",
        f"Ladder baseline: {metrics['ladder_baseline_accuracy']*100:.2f}%",
        "Prediction disclaimer standardized across every response",
    ])

    add_slide(prs, "Monitoring", [
        "Latency p50/p95, API 5xx rate",
        "Tool/model error rate",
        "Off-topic leak rate",
        "Prediction accuracy + calibration drift",
        "Weekly post-round refresh loop",
    ])

    add_slide(prs, "Limitations & next steps", [
        "Data ends 2025-09-27; live fixture/results source required",
        "Player availability not fully modeled",
        "Multi-turn state is not yet persisted across calls \u2014 weakest eval category by design margin",
        "Next: durable conversation state, shared rate-limit store, richer evaluation",
    ])

    prs.save(str(ROOT / "docs" / "stakeholder_demo_slides.pptx"))


if __name__ == "__main__":
    build()
    print("Wrote docs/stakeholder_demo_slides.pptx")
